@startuml use-cases
skin rose
left to right direction
skinparam actorStyle awesome

actor "User" as user


  package "Task management" as MVP {
    usecase "Create task" as create
    usecase "Complete task" as complete
    usecase "Delete task" as delete
    usecase "Relocate task" as relocate
  }

  package Navigation {
    usecase "View project" as view
    usecase "Collapse task subtree" as collapse_subtree
    usecase "Collapse to depth level" as collapse_depth
    usecase "Hide completed tasks" as hide_completed
  }

user --> MVP
user --> Navigation

@enduml
